apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-library
  namespace: default
  labels:
    app: community-library
    deployment: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: community-library
      deployment: blue
  template:
    metadata:
      labels:
        app: community-library
        deployment: blue
    spec:
      containers:
      - name: nginx
        image: asia.gcr.io/gorg-364804/community-library:0.0.8
        ports:
        - containerPort: 8080
        #no good stuff or probes just testing ACME so need to run some things